# important inbuilt libraries
from PIL import Image, ImageOps

# class
class ImageDeformer:
    def __init__(self, fileName : str) -> None:
        self.image = Image.open(fileName) # creating image object
        self.userMessage = None # stores message generated by any method
        return
    
    # provides user messege
    def getMessage(self):
        return self.userMessage
    
    # get image object
    def getImageObject(self, image : Image.Image) -> None:
        self.image = image
        return
    
    # set image obejct
    def provideImageObject(self) -> Image.Image:
        return self.image
    
    pass